version: '3'

silent: true

###############################################################################
tasks:
  default:
    cmds:
      - task: clean
      - task: run-samples-parallel
#==============================================================================
  test:
    cmds:
      - python -m unittest discover -s tests -p 'test_*.py'
#==============================================================================
  clean:
    cmds:
      - task: clean-samples
      - task: clean-py

  clean-samples:
    cmds:
      - rm -rf /tmp/dag*
      - rm -rf /tmp/node*
      - rm -rf ./.tmp

  clean-py:
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - find . -type d -name "*.pytest_cache" -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete
#==============================================================================
  sample-1:
    cmds:
      - python -B sample_1.py

  sample-2:
    cmds:
      - python -B sample_2.py

  sample-3:
    cmds:
      - python -B sample_3.py
  
  sample-4:
    cmds:
      - python -B sample_4.py
  
  sample-5:
    cmds:
      - python -B sample_5.py

  run-samples-parallel:
    deps: [sample-1, sample-2, sample-3, sample-4, sample-5]
    cmds:
      - echo "Taskfile Parallel Done!!!"
      - task: clean
#==============================================================================
